services:
    personal-homepage:
        image: golang:1.25.0-alpine3.22
        volumes:
            - ./:/app
        working_dir: /app
        restart: always
        ports:
            - "1234:8080"
        command: go run .
