services:
  personal-homepage:
    image: wlczak/personal-home-page:latest
    build: .
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    ports:
      - "1234:8080"
    networks:
      - personal-home-page-net

networks:
  personal-home-page-net:
    name: personal-home-page-net
