services:
    personal-homepage:
        image: wlczak/personal-home-page:latest
        volumes:
            # - ./:/app For local development
        working_dir: /app
        restart: always
        ports:
            - "1234:8080"
        command: ./PHP
