name: Build & Push Docker Image

on:
    push:
        branches: [ "main" ]

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - uses: actions/setup-node@v5

            - name: NPM install and build
              run: |
                  npm install
                  npm run build

            - uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/personal-home-page:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
